import type { CaseDelta, Comparison } from "./compare.js";
import { formatP } from "./stats.js";

export const COMMENT_MARKER = "<!-- evalgate -->";

/** Signed fixed-point number; rounds tiny values to an unsigned zero (never "-0.000"). */
export function fmtSigned(x: number, digits: number): string {
  const r = Number(x.toFixed(digits));
  if (r === 0) return (0).toFixed(digits);
  return `${r > 0 ? "+" : ""}${r.toFixed(digits)}`;
}

const score = (x: number | null) => (x === null ? "—" : x.toFixed(2));
const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
const label = (c: CaseDelta) => `\`${c.id}\`${c.critical ? " *(critical)*" : ""}`;

export function renderComment(c: Comparison): string {
  const lines: string[] = [COMMENT_MARKER, `### Evalgate: ${c.regression ? "FAIL" : "PASS"} — \`${c.suite}\``, ""];
  const passingDelta = c.head.passing - c.base.passing;
  lines.push(
    "| Metric | Base | Head | Delta |",
    "| --- | ---: | ---: | ---: |",
    `| Mean score | ${c.base.meanScore.toFixed(3)} | ${c.head.meanScore.toFixed(3)} | ${fmtSigned(c.head.meanScore - c.base.meanScore, 3)} |`,
    `| Cases passing | ${c.base.passing}/${c.base.cases} | ${c.head.passing}/${c.head.cases} | ${passingDelta > 0 ? "+" : ""}${passingDelta} |`,
    "",
    `Paired delta ${fmtSigned(c.delta, 3)} over ${c.paired} case(s) · one-sided permutation p = ${formatP(c.pValue)} · ` +
      `gate: minDelta ${c.gate.minDelta}, alpha ${c.gate.alpha}, caseThreshold ${c.gate.caseThreshold}`,
  );
  if (c.failures.length) lines.push("", "**Blocking**", ...c.failures.map((f) => `- ${esc(f)}`));
  if (c.warnings.length) lines.push("", "**Warnings**", ...c.warnings.map((w) => `- ${esc(w)}`));

  const changed = c.cases.filter((x) => x.status !== "unchanged");
  const unchanged = c.cases.filter((x) => x.status === "unchanged");
  lines.push("");
  if (changed.length) {
    lines.push(`#### Changed cases (${changed.length})`, "", "| Case | Base | Head | Delta | Status |", "| --- | ---: | ---: | ---: | --- |");
    for (const x of changed) {
      const head = x.status === "error" && x.head === null ? "error" : score(x.head);
      const delta = x.delta === null ? "—" : fmtSigned(x.delta, 2);
      lines.push(`| ${label(x)} | ${score(x.base)} | ${head} | ${delta} | ${x.status}${x.note ? `: ${esc(x.note)}` : ""} |`);
    }
  } else {
    lines.push("No case changed status.");
  }
  if (unchanged.length) {
    lines.push(
      "",
      `<details><summary>Unchanged cases (${unchanged.length})</summary>`,
      "",
      "| Case | Base | Head |",
      "| --- | ---: | ---: |",
      ...unchanged.map((x) => `| ${label(x)} | ${score(x.base)} | ${score(x.head)} |`),
      "",
      "</details>",
    );
  }
  lines.push("", "<sub>Generated by evalgate. Case scores are means over scorers and repeats (0 to 1).</sub>", "");
  return lines.join("\n");
}
